# -*- coding: utf-8 -*-
"""NLP_Model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDiFpOA8EazRf-zTi5Owh0n_fJXHg_iZ
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re
import string

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df = pd.read_csv("/content/new.csv", engine='python', on_bad_lines='warn')
df.head()

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')

#Remove stopwords
stop_words = set(stopwords.words('english'))
def remove_stopwords(text):
    text = str(text)  # convert to string (important)
    word_tokens = word_tokenize(text)  # tokenize
    filtered_sentence = [w for w in word_tokens if w.lower() not in stop_words]
    return " ".join(filtered_sentence)  # convert back to sentence

nltk.download('punkt_tab')
df['processed_text'] = df['cleaned_text'].apply(remove_stopwords)
df.head()

df[['cleaned_text','processed_text']]

#Remove rows that conatains null values
df = df.dropna(subset=['cleaned_text', 'reviews_rating'])

# Remove neutral rating (3)
df = df[df['reviews_rating'] != 3]

# Create performance column
df['performance'] = df['reviews_rating'].apply(
    lambda x: "Good" if x >= 4 else "Bad")

df[['reviews_rating','performance']].head()

y = df['reviews_rating']
y = df['performance']
X = df['cleaned_text']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

vectorizer = TfidfVectorizer(stop_words='english')
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

y_pred = model.predict(X_test_tfidf)

print("Accuracy:", accuracy_score(y_test, y_pred))

print('Classification Report:')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()